### ISSUE TITLE
Rename "chat bots" to "assistants"

### ISSUE THREAD

**Issue by cgillum** [Azure/azure-functions-openai-extension#17]
This issue tracks rebranding chat bots as assistants, which is consistent with OpenAI's naming conventions.

As part of this, we should also rename the "Agents" namespace to Assistants ("agent" is a misnomer, and we might decide to use it for something else later).

**Comment by manvkaur** [comment]
@aishwaryabh, @cgillum  Can we close this issue now?

**Comment by cgillum** [comment]
Yes! This was done as part of https://github.com/Azure/azure-functions-openai-extension/pull/35. Closing.
