### ISSUE TITLE
Readme for assistants should include creation of testdb database, my-todos container, and id for partition key

### ISSUE THREAD

**Issue by eamonoreilly** [Azure/azure-functions-openai-extension#39]
In the Readme.md for assistants, https://github.com/Azure/azure-functions-openai-extension/blob/main/samples/assistant/README.md#prerequisites, we should add instructions to create the testdb database, my-todos container, and id for partition key.

**Comment by manvkaur** [comment]
@eamonoreilly , Are we good to close this issue now?
I added the auto creation of db and container logic to nodejs sample as well.
