### ISSUE TITLE
Remove ability to use Azure OpenAI API keys

### ISSUE THREAD

**Issue by cgillum** [Azure/azure-functions-openai-extension#48]
### Expected Behavior

As part of a product review with executive leadership, an ask was made to remove the ability to use Azure OpenAI API keys. Instead, we should support only managed identity authentication with Azure OpenAI and our Azure-hosted search providers. This ensures that customers are always using the most secure configurations.

### Additional Information

Naturally, we'll want to support both system and user-assigned identities. New APIs may be required specifically for configuring user-assigned identities.

**Comment by manvkaur** [comment]
applies to Azure OpenAI, Kusto and Azure AI Search
